### ISSUE TITLE
Install dependency error

### ISSUE THREAD

**Issue by cephasteom** [FractalHQ/qwerty-keyboard#2]
Hi there,

This project looks great. Just what I need! I've installed it but am getting the following error:

`20:36:31 [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/svelte-piano/package/Instrument.js:1:58: ERROR: Could not resolve "tone"
node_modules/svelte-piano/package/Instrument.js:3:20: ERROR: Could not resolve "fractils"
node_modules/svelte-piano/package/Piano.svelte:36:20: ERROR: Could not resolve "../components/controls/Control.svelte"
    at failureErrorWithLog (/Users/peterthomas/Documents/code/ct-starter/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/peterthomas/Documents/code/ct-starter/node_modules/esbuild/lib/main.js:1056:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

I could obviously get around the first two by installing them within my project, but the third looks like a relative path error internal to svelte-piano.

Could you advise?

Many thanks in advance.

Pete.

**Comment by braebo** [comment]
Wow sorry @cephasteom I never actually finished this package!  I have a little more time now so I'm trying to get it sorted.  It should be fixed now, but hopefully you were able to just copy/paste anything you might have needed at the time 😅. Sorry for any time you might have wasted poking at this thing!
